### ISSUE TITLE
Error: Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by nileshbandekar** [utropicmedia/storj-nodejs#2]
D:\fileUploadDemo\node_modules\ffi-napi\lib\dynamic_library.js:76
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (D:\fileUploadDemo\node_modules\ffi-napi\lib\dynamic_library.js:76:11)
    at Object.Library (D:\fileUploadDemo\node_modules\ffi-napi\lib\library.js:45:14)
    at Object.<anonymous> (D:\fileUploadDemo\node_modules\storj-nodejs\libUplinkNode.js:168:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by nileshbandekar** [comment]
My Bad 
just copy-pasted  "go build -o libuplinkc**.so** -buildmode=c-shared" on windows
corrected to "go build -o libuplinkc**.dll** -buildmode=c-shared"
