### ISSUE TITLE
Windows "node-gyp rebuild" getting below error 

### ISSUE THREAD

**Issue by nileshbandekar** [utropicmedia/storj-nodejs#5]
Installed storj-nodejs Node.js package
without executing preinstall script since its syntax is breaking in windows.
downloaded  windows-build-tools 
but while executing pre-install scripts manually  
### for node-gyp rebuild getting below error

C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.1 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\RDP_Con\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1033) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\RDP_Con\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\RDP_Con\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RDP_Con\\Documents\\xxx\\node_modules\\storj-nodejs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RDP_Con\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RDP_Con\\AppData\\Local\\node-gyp\\Cache\\12.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\RDP_Con\\AppData\\Local\\node-gyp\\Cache\\12.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\RDP_Con\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\RDP_Con\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\RDP_Con\\Documents\\xxx\\node_modules\\storj-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\RDP_Con\\Documents\\xxx\\node_modules\\storj-nodejs\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  libUplink.cc
  win_delay_load_hook.cc
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(15): error
C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\libUplink
.cc) [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(15): error
C2146: syntax error: missing ';' before identifier 'GoUintptr' (compiling source file ..\libUplink.cc) [C:\Users\RDP_Co
n\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(18): error
C2146: syntax error: missing ';' before identifier 'GoComplex64' (compiling source file ..\libUplink.cc) [C:\Users\RDP_
Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(18): error
C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\libUplink
.cc) [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(19): error
C2371: '_Complex': redefinition; different basic types (compiling source file ..\libUplink.cc) [C:\Users\RDP_Con\Docume
nts\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(18): note
  : see declaration of '_Complex' (compiling source file ..\libUplink.cc)
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(19): error
C2146: syntax error: missing ';' before identifier 'GoComplex128' (compiling source file ..\libUplink.cc) [C:\Users\RDP
_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\build\cgo-gcc-export-header-prolog(19): error
C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\libUplink
.cc) [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(140): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(140): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(140): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(180): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(180): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(180): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(193): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(193): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(193): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(234): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(234): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(234): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(278): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(278): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(278): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(365): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(365): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(365): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(428): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(428): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(428): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(436): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(436): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(436): note: see usage of 'conve
  rtedvalueenc'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(487): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(487): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(487): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(646): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(646): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(646): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(717): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(717): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(717): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(741): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(741): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(741): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(973): error C2131: expression did
 not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodejs
.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(973): note: failure was caused
  by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(973): note: see usage of 'conve
  rtedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1146): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1146): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1146): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1476): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1476): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1476): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1532): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1532): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1532): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1688): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1688): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1688): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1700): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1700): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1700): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1712): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1712): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(1712): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2046): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2046): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2046): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2279): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2279): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2279): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2366): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2366): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2366): note: see usage of 'rest
  rictionsSize'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2384): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2384): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2384): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2395): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2395): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2395): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2400): error C3863: array type 'E
ncryptionRestriction [restrictionsSize]' is not assignable [C:\Users\RDP_Con\Documents\xxx\node_modules
\storj-nodejs\build\storjnodejs.vcxproj]
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2532): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2532): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2532): note: see usage of 'conv
  ertedvalue'
c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2694): error C2131: expression di
d not evaluate to a constant [C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs\build\storjnodej
s.vcxproj]
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2694): note: failure was caused
   by a read of a variable outside its lifetime
  c:\users\rdp_con\documents\xxx\node_modules\storj-nodejs\libuplink.cc(2694): note: see usage of 'conv
  ertedvalue'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\RDP_Con\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RDP_Con\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\RDP_Con\Documents\xxx\node_modules\storj-nodejs
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

### binding.gyp
{
  'targets': [
    {
      'target_name': 'storjnodejs',
      'sources': [ './libUplink.cc'],
      "include_dirs":["./"],
      "libraries":["<(module_root_dir)/libuplinkc.dll"],
      "ldflags": ["-Wl,-rpath,'$$ORIGIN'"],
      "cflags_cc": ["-fexceptions","-fPIC","-Wno-unknown-pragmas"]
    }
  ]
}

**Comment by kmozurkewich** [comment]
@nileshbandekar - we just published a new release.  Can you retry and comment?
