### ISSUE TITLE
Error `pacemonkeygo/monkit expects import` when installing uplink 

### ISSUE THREAD

**Issue by hunterInt** [utropicmedia/storj-nodejs#6]
I have verified that `$GOPATH/bin` is in my `$PATH`. The command `go get storj.io/uplink-c` returns this error:

```package github.com/spacemonkeygo/monkit/v3: code in directory /home/hunter/go/src/github.com/spacemonkeygo/monkit expects import "github.com/spacemonkeygo/monkit/v3"```

How can I solve this issue?

**Comment by kmozurkewich** [comment]
Hi @hunterInt  - two things.  First, make sure to remove any old versions/references to storj.io/uplink-c from your GOPATH (check under $GOPATH/src).  Second, try running 'npm install storj-nodejs'
The error you're getting is due to an old reference.

**Comment by hunterInt** [comment]
Hello @kmozurkewich
Thanks for the quick response! I have tried removing go entirely and removed all folders under the `$GOPATH/src` directory, then I reinstalled go and re-ran the `go get storj.io/uplink-c` command, but I still get the same error. 

I then tried running  `npm install storj-nodejs` (installing `0.10.1`) and this is the error I got:
```

> storj-nodejs@0.10.1 preinstall /home/hunter/Documents/projects/sharp/node_modules/storj-nodejs
> node build.js

Error :  Error: Command failed: ((cd /home/hunter/go/src/storj.io/uplink-c && go build -o libuplinkc.so -buildmode=c-shared ) && cp /home/hunter/go/src/storj.io/uplink-c/libuplinkc.* ./ && cp /home/hunter/go/src/storj.io/uplink-c/uplink_definitions.h ./ && node-gyp configure && node-gyp rebuild)
../uplink/common.go:11:2: code in directory /home/hunter/go/src/github.com/spacemonkeygo/monkit expects import "github.com/spacemonkeygo/monkit/v3"

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '((cd /home/hunter/go/src/storj.io/uplink-c && go build -o libuplinkc.so -buildmode=c-shared ) && cp /home/hunter/go/src/storj.io/uplink-c/libuplinkc.* ./ && cp /home/hunter/go/src/storj.io/uplink-c/uplink_definitions.h ./ && node-gyp configure && node-gyp rebuild)'
}

> storj-nodejs@0.10.1 install /home/hunter/Documents/projects/sharp/node_modules/storj-nodejs
> (node-gyp configure) && (node-gyp rebuild)

make: Entering directory '/home/hunter/Documents/projects/sharp/node_modules/storj-nodejs/build'
  CXX(target) Release/obj.target/storjnodejs/libUplink.o
../libUplink.cc:3:10: fatal error: uplink_definitions.h: No such file or directory
    3 | #include "uplink_definitions.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [storjnodejs.target.mk:113: Release/obj.target/storjnodejs/libUplink.o] Error 1
make: Leaving directory '/home/hunter/Documents/projects/sharp/node_modules/storj-nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hunter/Documents/projects/sharp/node_modules/storj-nodejs
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sharp@0.2.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storj-nodejs@0.10.1 install: `(node-gyp configure) && (node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storj-nodejs@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hunter/.npm/_logs/2020-04-22T18_20_32_482Z-debug.log

```

**Comment by kmozurkewich** [comment]
@hunterInt  - this is an error in the build.  Basically to fix you need to clone the repo at https://github.com/storj/uplink-c into your $GOPATH/src directory and re-run the build.

We'll have a fix for this next week - the general bug affects all of our storj  bindings.

Thanks for the feedback - very appreciated and helpful.

**Comment by hunterInt** [comment]
@kmozurkewich I'm not too familiar with GO, but I tried cloneing that repo into the `$GOPATH/src` directory like you said then ran `go build` (which I'm assuming is correct), however, I still got this error:

```
hunter@G3-571:~/go/src/storj.io/uplink-c$ go build
../uplink/common.go:11:2: code in directory /home/hunter/go/src/github.com/spacemonkeygo/monkit expects import "github.com/spacemonkeygo/monkit/v3"
```
Note, I did clone the repo inside `/storj.io/` since it followed the same folder structure as the `go get storj.io/uplink-c` would have. 

Is this correct? Is there anything else I can try to get this to work? 

Thanks!

**Comment by shivam201312** [comment]
@hunterInt What is your current version of golang ?
I have faced similar issue regarding github.com/spacemonkeygo/monkit/v3 
my golang version was 1.6 . i have removed older version and installed golang 1.14 . It worked for me .

**Comment by hunterInt** [comment]
@shivam201312 I downgraded to 1.14 as you suggested here were the outcomes:

- When I ran `go get storj.io/uplink-c` I got:
```
# storj.io/common/rpc/rpcpool
/home/hunter/go/src/storj.io/common/rpc/rpcpool/pool.go:73:5: cannot use (*Conn)(nil) (type *Conn) as type drpc.Conn in assignment:
	*Conn does not implement drpc.Conn (missing Closed method)
```

- However, When I tried manually cloning the repo at https://github.com/storj/uplink-c into my $GOPATH/src directory and ran `go build` plus`npm install storj-nodejs` it seems to be working correctly now. 

Thanks for the tip!

**Comment by shivam201312** [comment]
@hunterInt 
After running go get storj.io/uplink-c 
```
# storj.io/common/rpc/rpcpool
/home/hunter/go/src/storj.io/common/rpc/rpcpool/pool.go:73:5: cannot use (*Conn)(nil) (type *Conn) as type drpc.Conn in assignment:
	*Conn does not implement drpc.Conn (missing Closed method)
```
it shows warning  but it does not affect working of story-nodejs module  , you can just run 
```
go get storj.io/uplink-c 
npm install storj-nodejs
```

**Comment by hunterInt** [comment]
@shivam201312 oh that's helpful! Thanks!

**Comment by kmozurkewich** [comment]
resolved in latest version. (1.0.2)
